# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  dimensions:
    columns: 100
    lines: 35 
#  position:
#    x: 75
#    y: 75
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none
  startup_mode: Windowed
  title: Alacritty

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic

  # Point size
  size: 12

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 5

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

 
  use_thin_strokes: false

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

schemes:
  snazzy: &snazzy
    primary:
      background: '#282a36'
      foreground: '#eff0eb'
    normal:
      black:   '0x282a36'
      red:     '0xff5c57'
      green:   '0x5af78e'
      yellow:  '0xf3f99d'
      blue:    '0x57c7ff'
      magenta: '0xff6ac1'
      cyan:    '0x9aedfe'
      white:   '0xf1f1f0'
    bright:
      black:   '0x686868'
      red:     '0xff5c57'
      green:   '0x5af78e'
      yellow:  '0xf3f99d'
      blue:    '0x57c7ff'
      magenta: '0xff6ac1'
      cyan:    '0x9aedfe'
      white:   '0xf1f1f0'
  gruvbox: &gruvbox
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    cursor:
      text: '0x2E3440'
      cursor: '0xD8DEE9'
    normal:
      black: '0x3B4252'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x88C0D0'
      white: '0xE5E9F0'
    bright:
      black: '0x4C566A'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x8FBCBB'
      white: '0xECEFF4'
  kde_breeze: &kde_breeze
    primary:
      background: '#232627'
      foreground: '#fcfcfc'
      dim_foreground: '#eff0f1'
      bright_foreground: '#ffffff'
      dim_background: '#31363b'
      bright_background: '#000000'
    normal:
      black: '#232627'
      red: '#ed1515'
      green: '#11d116'
      yellow: '#f67400'
      blue: '#1d99f3'
      magenta: '#9b59b6'
      cyan: '#1abc9c'
      white: '#fcfcfc'
    bright:
      black: '#7f8c8d'
      red: '#c0392b'
      green: '#1cdc9a'
      yellow: '#fdbc4b'
      blue: '#3daee9'
      magenta: '#8e44ad'
      cyan: '#16a085'
      white: '#ffffff'
    dim:
      black: '#31363b'
      red: '#783228'
      green: '#17a262'
      yellow: '#b65619'
      blue: '#1b668f'
      magenta: '#614a73'
      cyan: '#186c60'
      white: '#63686d'
colors: *snazzy


  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '' }`
  #
  # indexed_colors: []

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 0.95

#selection:
#semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
window.dynamic_title: true

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Underline

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

  # Live config reload (changes require restart)
  live_config_reload: true

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
shell:
  program: /usr/bin/zsh
  args:
    - --login

# Startup directory
#
# Directory the shell is started in. If this is unset, or `None`, the working
# directory of the parent process will be used.
working_directory: /home/rc/


mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: false

url:
  # URL launcher
  #
  # This program is executed when clicking on a text which is recognized as a URL.
  # The URL is always added to the command as the last parameter.
  #
  # When set to `None`, URL launching will be disabled completely.
  #
  # Default:
  #   - (macOS) open
  #   - (Linux/BSD) xdg-open
  #   - (Windows) explorer
  launcher:
    program: xdg-opem
    args: []
# URL modifiers
#
# These are the modifiers that need to be held down for opening URLs when clicking
# on them. The available modifiers are documented in the key binding section.
#modifiers: None

key_bindings:
  - { key: V,        mods: Control,       action: Paste                        }
  - { key: C,        mods: Control,       action: Copy                         }
  - { key: N,        mods: Control,       action: SpawnNewInstance             }
